import pandas as pd

# ----------------------------
# Load Dataset
# ----------------------------
df = pd.read_csv("data/sales_dataset.csv")

print("Original Shape:", df.shape)

# ----------------------------
# Missing Values
# ----------------------------
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing values
df.fillna(0, inplace=True)

# ----------------------------
# Remove Duplicates
# ----------------------------
duplicates = df.duplicated().sum()
print("\nDuplicate Rows:", duplicates)

df.drop_duplicates(inplace=True)

# ----------------------------
# Convert Date
# ----------------------------
df["full_date"] = pd.to_datetime(df["full_date"])

# ----------------------------
# Sort Data
# ----------------------------
df = df.sort_values(
    by=["product_key", "store_key", "full_date"]
)

print("\nShape After Cleaning:", df.shape)

# ==========================================================
# Feature Engineering
# ==========================================================

# Lag Features
df["lag_1"] = (
    df.groupby(["product_key", "store_key"])["quantity"]
    .shift(1)
)

df["lag_3"] = (
    df.groupby(["product_key", "store_key"])["quantity"]
    .shift(3)
)

df["lag_7"] = (
    df.groupby(["product_key", "store_key"])["quantity"]
    .shift(7)
)

# Rolling Mean Features
df["rolling_mean_3"] = (
    df.groupby(["product_key", "store_key"])["quantity"]
    .transform(lambda x: x.shift(1).rolling(window=3).mean())
)

df["rolling_mean_7"] = (
    df.groupby(["product_key", "store_key"])["quantity"]
    .transform(lambda x: x.shift(1).rolling(window=7).mean())
)

# ==========================================================
# IMPORTANT
# Do NOT drop rows
# Fill NaN generated by lag features
# ==========================================================

lag_columns = [
    "lag_1",
    "lag_3",
    "lag_7",
    "rolling_mean_3",
    "rolling_mean_7"
]

df[lag_columns] = df[lag_columns].fillna(0)

# ----------------------------
# Save Dataset
# ----------------------------
df.to_csv(
    "data/featured_sales_dataset.csv",
    index=False
)

print("\n===================================")
print("Feature Engineering Completed!")
print("===================================")

print("Final Shape:", df.shape)

print("\nFirst 5 Rows:")
print(df.head())